//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *GPUInferenceAutoscaler) DeepCopyInto(out *GPUInferenceAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject implements runtime.Object.
func (in *GPUInferenceAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy.
func (in *GPUInferenceAutoscaler) DeepCopy() *GPUInferenceAutoscaler {
	if in == nil {
		return nil
	}
	out := new(GPUInferenceAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for Spec.
func (in *GPUInferenceAutoscalerSpec) DeepCopyInto(out *GPUInferenceAutoscalerSpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Prediction != nil {
		in, out := &in.Prediction, &out.Prediction
		*out = new(PredictionSpec)
		**out = **in
	}
	if in.ColdStart != nil {
		in, out := &in.ColdStart, &out.ColdStart
		*out = new(ColdStartSpec)
		**out = **in
	}
	if in.SyncPeriodSeconds != nil {
		in, out := &in.SyncPeriodSeconds, &out.SyncPeriodSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopyInto for MetricSpec.
func (in *MetricSpec) DeepCopyInto(out *MetricSpec) {
	*out = *in
	if in.QueueConfig != nil {
		in, out := &in.QueueConfig, &out.QueueConfig
		*out = new(QueueMetricConfig)
		**out = **in
	}
}

// DeepCopyInto for Status.
func (in *GPUInferenceAutoscalerStatus) DeepCopyInto(out *GPUInferenceAutoscalerStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentMetrics != nil {
		in, out := &in.CurrentMetrics, &out.CurrentMetrics
		*out = make([]MetricValue, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for List.
func (in *GPUInferenceAutoscalerList) DeepCopyInto(out *GPUInferenceAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUInferenceAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject for List.
func (in *GPUInferenceAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy for List.
func (in *GPUInferenceAutoscalerList) DeepCopy() *GPUInferenceAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(GPUInferenceAutoscalerList)
	in.DeepCopyInto(out)
	return out
}
